In [1]:
# simplex implementation

# min -4x1 - 2x2
#
# with constraints
# 4x1 + 6x2 <= 24,
# 2x1 + 2x2 <= 6,
# x1, x2 >= 0

In [13]:
import numpy as np

In [14]:
C = np.array([-4, -2, 0, 0])  # coefficients of the objective function
A = np.array([[4, 6, 1, 0], [2, 0, 0, 1]])  # equality constraints
b = np.array([24, 6])  # right hand side of the equality constraints
x = np.array([0, 0, 24, 6])  # initial basic feasible solution

In [18]:
B_pretty = np.array([3, 4])
N_pretty = np.array([1, 2])

In [19]:
for i in range(10):
    # 0)
    B = A[:, B_pretty - 1]
    N = A[:, N_pretty - 1]

    C_B = C[B_pretty - 1]
    C_N = C[N_pretty - 1]

    X_B = x[B_pretty - 1]
    X_N = x[N_pretty - 1]

    print("Iteration:", i + 1)
    print("B set:", B_pretty)
    print("N set:", N_pretty)
    print("B:", B)
    print("N:", N)
    print("C_B:", C_B)
    print("X_B:", X_B)
    print("C_N:", C_N)
    print("X_N:", X_N)
    print()

    # 1)
    lambda_ = np.dot(np.linalg.inv(B.T), C_B)
    print("lambda:", lambda_)

    # 2)
    s_n = C_N - np.dot(N.T, lambda_)
    print("s_n:", s_n)

    # 3)
    if all(s_n >= 0):
        print("Optimal solution found")
        print("X_B:", X_B)
        print("X_N:", X_N)
        break

    # 4)
    j = np.argmin(s_n)
    print("j:", j)

    # 5)
    d = np.dot(np.linalg.inv(B), A[:, j])
    print("d:", d)

    # 6)
    if all(d <= 0):
        print("Unbounded solution")
        break

    # 7)
    theta = np.inf
    p = -1
    for i in range(len(d)):
        if d[i] > 0:
            if X_B[i] / d[i] < theta:
                theta = X_B[i] / d[i]
                p = i

    print("theta:", theta)
    print("p:", p)

    # 8)

    # idk whats now
    X_B = X_B - theta * d
    X_B[p] = theta
    X_N[j] = theta

    B[:, p] = A[:, j]
    C_B[p] = C_N[j]

    N[:, j] = A[:, p]
    C_N[j] = C[j]

    B_pretty[p], N_pretty[j] = N_pretty[j], B_pretty[p]
    B, N = N, B
    C_B, C_N = C_N, C_B
    X_B, X_N = X_N, X_B

[[1 0]
 [0 1]]
[[4 6]
 [2 0]]
Iteration: 1
B: [3 1]
N: [4 2]
C_B: [-4, -2]
X_B: [3.0, 0]
C_N: [0, -4]
X_N: [12.  3.]
B [[6 6]
 [0 0]]
N [[1 4]
 [0 2]]

[[1 4]
 [0 2]]
[[0 6]
 [1 0]]
Iteration: 1
B: [3 4]
N: [1 2]
C_B: [-4, -4]
X_B: [0. 3.]
C_N: [-4, 0]
X_N: [3. 0.]
B [[6 6]
 [0 0]]
N [[1 4]
 [0 2]]

[[1 0]
 [0 1]]
[[4 6]
 [2 0]]
Optimal solution found
X_B: [0. 3.]
X_N: [3. 0.]
